name: Submit Azure ML Job
on:
  push:
    branches:
      - staging
jobs:
  submit_aml_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run Unit Test
      run: |
        python -m unittest discover -s production -p "test_*.py"
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli
    - name: Install Azure ML Extension
      run: |
        az extension add -n ml -y
    - name: Submit Azure ML Job
      run: |
        ls production/
        az ml job create --file production/job.yaml --resource-group cw_resourcegrp --workspace-name cw_workspace
