# name: Azure GitHub Actions
# run-name: ${{ github.actor }} workflow test
# on: [push]
# jobs:
#   testJob:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hi! I'm running because of a ${{ github.event_name }} event."
#       - run: echo "Checking out the repository from ${{ github.repository }}."
#       - name: Clone repository code
#         uses: actions/checkout@v4
#       - run: echo "Repository cloned, I think I'm ready. The files look like this:"
#       - name: List files
#         run: ls ${{ github.workspace }}
#       - name: Log in to Azure
#         uses: azure/login@v1
#         with:
#           creds: '${{ secrets.AZURE_CREDENTIALS }}'
#       - name: Test azure login by getting details
#         run: az account show

# name: Submit Azure ML Job
# on:
#   push:
#     branches:
#       - main
# jobs:
#   submit_aml_job:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2
#     - name: Azure Login
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#     - name: Install Azure CLI
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y azure-cli
#     - name: Install Azure ML Extension
#       run: |
#         az extension add -n ml -y
#     - name: Submit Azure ML Job
#       run: |
#         ls ../../production/


# az ml job create --file ../../production/job.yaml --resource-group cw_practical --workspace-name cw_practical

name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Working Directory
      run: |
        pwd
        ls -la